# Generated by Django 2.1.5 on 2019-03-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bug',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
