# Generated by Django 2.1.5 on 2019-03-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_auto_20190306_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
