# Generated by Django 2.1.5 on 2019-03-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_auto_20190325_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
