# Generated by Django 2.1.2 on 2018-12-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20181216_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostelImages',
            new_name='HostelImage',
        ),
        migrations.RenameModel(
            old_name='RoomImages',
            new_name='RoomImage',
        ),
        migrations.AlterField(
            model_name='room',
            name='house_type',
            field=models.CharField(choices=[('1B', 'One Bedroom'), ('2B', 'Two Bedroom'), ('BS', 'Bedsitter'), ('JD', 'John Doe')], max_length=2),
        ),
    ]
