# Generated by Django 2.1.2 on 2018-12-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20181216_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
