# Generated by Django 2.1.2 on 2018-12-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_hostel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostel',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='hostel',
            name='bathrooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='toilet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='water',
            field=models.BooleanField(default=False),
        ),
    ]
