# Generated by Django 2.1.2 on 2018-12-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20181221_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='toilet',
        ),
    ]
