# Generated by Django 2.1.2 on 2018-12-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20181221_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='price_range',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
