# Generated by Django 2.1.2 on 2018-12-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_hostel_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tallied',
            field=models.BooleanField(default=False),
        ),
    ]
