# Generated by Django 2.1.2 on 2018-12-31 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_room_tallied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
    ]
