# Generated by Django 2.1.2 on 2018-12-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20181231_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
