# Generated by Django 2.1.2 on 2018-12-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20181231_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(help_text='Enter your preferred name', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(help_text='Enter phone number', max_length=10),
        ),
    ]
