# Generated by Django 2.1.2 on 2018-12-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20181231_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='all_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
