# Generated by Django 2.1.5 on 2019-02-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_auto_20190207_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
