# Generated by Django 2.1.5 on 2019-03-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_remove_booking_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
