# Generated by Django 2.1.5 on 2019-03-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_auto_20190313_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(help_text='Preferred name of the premises', max_length=400, unique=True),
        ),
    ]
