# Generated by Django 2.1.5 on 2019-03-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_auto_20190313_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
