# Generated by Django 2.1.5 on 2019-03-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_booking_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='bs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='one',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='sr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='two',
            field=models.IntegerField(default=0),
        ),
    ]
