# Generated by Django 2.1.5 on 2019-03-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_auto_20190321_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
