# Generated by Django 2.1.5 on 2019-03-21 15:42

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_roomimage_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='processed',
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='file',
            field=models.ImageField(help_text='PLEASE CROP TO 16:9', upload_to=book.models.upload_hostel_to),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='file',
            field=models.ImageField(help_text='PLEASE CROP TO 16:9', upload_to=book.models.upload_room_to),
        ),
    ]
